# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "uas"
    "sdhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    #    device = "/dev/disk/by-uuid/492ba4ca-7e4d-4974-a27c-ae3a3a696c75";
    #    fsType = "ext4";
    device = "zroot/nixos";
    fsType = "zfs";
    #options = [ "zfsutil" ];
  };

  fileSystems."/home" = {
    device = "zroot/nixos/home";
    fsType = "zfs";
    #options = [ "zfsutil" ];
  };

  #boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/db80184c-8bb3-41f4-9810-74f72c0fc4be";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/796B-1719";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [
    {
      device = "/var/lib/swapfile";
      size = 16 * 1024;
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
